### ISSUE TITLE
Timeout 408

### ISSUE THREAD

**Issue by SmirnovM91** [bifot/micromq#52]
![image](https://user-images.githubusercontent.com/32675072/75113750-90967600-567a-11ea-9c17-5b10d342e137.png)
![image](https://user-images.githubusercontent.com/32675072/75113757-98eeb100-567a-11ea-9b1b-3768114c1a20.png)
![image](https://user-images.githubusercontent.com/32675072/75113763-9e4bfb80-567a-11ea-80b0-b33b033898e7.png)

  rabbitmqUrl: "amqp://guest:guest@localhost:5672"

I am trying to POST on /1c/users and got 408 timeout? Could you help me ?

**Comment by bifot** [comment]
Is rabbit okay and message passed to the queue?
